trigger:
- master

stages:
- stage: 'Build'
  displayName: 'Build'
  variables:
    GOVERSION: '1.18'   # Version of Go tools used for building and testing
    CGO_ENABLED: '0'      # Disable cgo to get a static binary
    GOOS: 'linux'
    GOARCH: 'amd64'
  jobs:
  - job: BuildBackend
    displayName: 'Build Go Backend'
    pool:
      vmImage: 'Ubuntu 18.04'
    steps:
    - task: GoTool@0
      inputs:
        version: $(GOVERSION)
      displayName: 'Install and select Go version $(GOVERSION)'

    - task: Go@0
      inputs:
        command: 'build'
        arguments: '-a -o demo'
      displayName: 'Build Go app'

    - publish: '$(Build.SourcesDirectory)/demo'
      artifact: 'Executable'
      displayName: 'Publish pipeline artifact'

    - task: PublishCodeCoverageResults@1
      condition: always()
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Build.SourcesDirectory)/demo-coverage.xml'
      displayName: 'Publish code coverage results'
