trigger:
- master

stages:
- stage: 'Build'
  displayName: 'Build'
  variables:
    GOVERSION: '1.18'   # Version of Go tools used for building and testing
    CGO_ENABLED: '0'      # Disable cgo to get a static binary
    GOOS: 'linux'
    GOARCH: 'amd64'
  jobs:
  - job: BuildBackend
    displayName: 'Build Go Backend'
    pool:
      vmImage: 'Ubuntu 18.04'
    steps:
    - task: GoTool@0
      inputs:
        version: $(GOVERSION)
      displayName: 'Install and select Go version $(GOVERSION)'

    - task: Go@0
      inputs:
        command: 'build'
        arguments: '-a -o demo'
      displayName: 'Build Go app'

    - publish: '$(Build.SourcesDirectory)/demo'
      artifact: 'Executable'
      displayName: 'Publish pipeline artifact'

    - task: PublishCodeCoverageResults@1
      condition: always()
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Build.SourcesDirectory)/demo-coverage.xml'
      displayName: 'Publish code coverage results'
- stage: PublishImage
  displayName: 'Publish Docker Image'
  jobs:
  - job: PublishImage
    displayName: 'Publish Docker Image'
    pool:
      vmImage: 'Ubuntu 18.04'
    steps:
    - download: current
      artifact: Executable
      displayName: 'Download pipeline artifact'

    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Agent.BuildDirectory)/Executable'
        CleanTargetFolder: false
        Contents: demo
        TargetFolder: '$(Build.SourcesDirectory)'
      displayName: 'Copy executable to folder with dockerfile'

    - task: Docker@2
      displayName: 'Login to docker hub'
      inputs:
        command: login
        containerRegistry: 'fibonacci'
    - task: Docker@2
      displayName: 'Build and Push Image'
      inputs:
        command: buildAndPush
        repository: andrew1000/fibonacci
        tags: |
          latest
          $(Build.BuildId)

- stage: PublishToAzure
  displayName: 'Publish App to Azure'
  jobs:
  - job: PublishToAzure
    displayName: 'Publish App to Azure'
    pool:
      vmImage: 'Ubuntu 18.04'
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'fibonacci'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'fibonacci'
        location: 'eastus'
        templateLocation: 'Linked artifact'
        csmFile: 'azuredeploy.json'
        overrideParameters: '-siteName fibonacci -demoAppImageVersion $(Build.BuildId)'
        deploymentMode: 'Incremental'
      displayName: 'Create or Update Azure Resource Group'

    - script: |
        curl --fail --max-time 15 https://fibonacci.azurewebsites.net/fibon 2>&1
        if [ $? -ne 0 ]; then
          >&2 echo "Website not reachable"
        fi
      displayName: 'Try deployed web service'
      failOnStderr: true
